In syscalls.py now
firstcall.py called with 5 arguments
The time is now Wed Apr 11 13:54:00 2007
firstcall exited with status 1
firstcall.py called with 5 arguments
The time is now Wed Apr 11 13:54:00 2007
The process ID is 25023
